# https://github.com/probot/settings

repository:
    allow_mege_commit: true
    allow_rebase_merge: false  # Usually not required, and risky enough that it should be done manually
    allow_squash_merge: true
    default_branch: root
    has_downloads: false  # Most projects don't need to produce release builds
    has_issues: true
    has_projects: true
    has_wiki: false  # We have our own documentation elsewhere
    homepage: https://kordex.dev
    topics: kotlin

teams:
    - name: admins
      permission: admin

    - name: developers
      permission: push

branches:
    - name: root

      protection:
        required_pull_request_reviews:
            dismiss_stale_reviews: true
            require_code_owner_reviews: false
            required_approving_review_count: 1

            dismissal_restrictions:
                teams:
                    - admins
                    - developers
        
        required_status_checks:
            strict: true
        
        restrictions:
            teams:
                - admins
                - developers
